version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.7
    environment:
      CLICKHOUSE_DB: tensorzero
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: chpassword
    ports:
      - "8123:8123"
    restart: unless-stopped

  gateway:
    image: tensorzero/gateway:latest
    depends_on:
      - clickhouse
    env_file: .env
    volumes:
      - ./config:/app/config:ro
    command: --config-file /app/config/tensorzero.toml
    ports:
      - "${GATEWAY_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  ui:
    image: tensorzero/ui:latest
    depends_on:
      - gateway
    volumes:
      - ./config:/app/config:ro
    env_file:
      - .env
    environment:
      # Point UI at the same ClickHouse + Gateway
      TENSORZERO_CLICKHOUSE_URL: ${TENSORZERO_CLICKHOUSE_URL}
      TENSORZERO_GATEWAY_URL: http://gateway:3000
    ports:
      - "4000:4000"
    restart: unless-stopped
